pipeline {
  agent {
    docker {
      image 'parikshitdesai388/react-jenkins-agent:latest'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
    }
  }

  environment {
    APP_DIR = "Stock"

    // ---------- SONARQUBE ----------
    SONAR_URL = "http://50.19.150.173:9000"
    SONAR_PROJECT_KEY = "react-frontend"

    // ---------- DOCKER ----------
    IMAGE_NAME  = "parikshitdesai388/cicd"
    IMAGE_TAG   = "${BUILD_NUMBER}"
    DOCKER_IMAGE = "${IMAGE_NAME}:${IMAGE_TAG}"

    // ---------- GITOPS ----------
    GITOPS_REPO = "react-gitops-manifests"
    GIT_USER    = "Parikshit09-coder"
  }

  stages {

    /* ================= CHECKOUT ================= */
    stage('Checkout Source') {
      steps {
        checkout scm
        sh 'ls -ltr'
      }
    }

    /* ================= INSTALL ================= */
    stage('Install Dependencies') {
      steps {
        dir(env.APP_DIR) {
          sh 'npm ci'
        }
      }
    }

    /* ================= BUILD ================= */
    stage('Build React App') {
      steps {
        dir(env.APP_DIR) {
          sh 'npm run build'
        }
      }
    }

    /* ================= SONARQUBE ================= */
    stage('Static Code Analysis') {
      steps {
        dir(env.APP_DIR) {
          withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_TOKEN')]) {
            sh '''
              npx sonar-scanner \
                -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                -Dsonar.sources=src \
                -Dsonar.host.url=${SONAR_URL} \
                -Dsonar.login=${SONAR_TOKEN}
            '''
          }
        }
      }
    }

    /* ================= DOCKER BUILD ================= */
    stage('Build Docker Image') {
      steps {
        sh 'docker build -t ${DOCKER_IMAGE} Stock'
      }
    }

    /* ================= DOCKER PUSH ================= */
    stage('Push Docker Image') {
      steps {
        script {
          docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
            docker.image("${DOCKER_IMAGE}").push()
          }
        }
      }
    }

    /* ================= UPDATE GITOPS ================= */
    stage('Update Deployment Manifest') {
      steps {
        withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
          sh '''
            rm -rf gitops
            git clone https://${GITHUB_TOKEN}@github.com/${GIT_USER}/${GITOPS_REPO}.git gitops

            cd gitops
            git config user.email "gurudesai2005@gmail.com"
            git config user.name "Parikshit09-coder"

            sed -i "s|image: .*|image: ${DOCKER_IMAGE}|" deployment.yaml

            git add deployment.yaml
            git commit -m "Update image to ${IMAGE_TAG}"
            git push origin main
          '''
        }
      }
    }
  }

  post {
    success {
      echo "CI pipeline completed successfully 🚀"
    }
    failure {
      echo "CI pipeline failed ❌"
    }
  }
}
